service: flickr-challenge-api

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  role: arn:aws:iam::733317892132:role/lambda_vpc_basic_execution
  versionFunctions: true
  vpc:
    securityGroupIds:
      - sg-085a3d2d54cbfec2d
    subnetIds:
      - subnet-05f7737d2791ebc4f
package:
  individually: true
  exclude:
    - ./**
functions:
  index:
    name: get_flickr_photos
    handler: index.handler
    timeout: 240
    package:
      include:
        - index.js
        - src/**
        - node_modules/**
    events:
      - http:
          path: photos
          method: post
          cors: true
    environment:
      FLICKR_API_KEY: ${env:FLICKR_API_KEY}
